<?php
/**
 * MageWorkshop
 * Copyright (C) 2012  MageWorkshop <mageworkshophq@gmail.com>
 *
 * NOTICE OF LICENSE
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see http://opensource.org/licenses/gpl-3.0.html.
 *
 * @category   MageWorkshop
 * @package    MageWorkshop_DetailedReview
 * @copyright  Copyright (c) 2012 MageWorkshop Co. (http://mage-workshop.com)
 * @license    http://opensource.org/licenses/gpl-3.0.html GNU General Public License, version 3 (GPL-3.0)
 * @author     MageWorkshop <mageworkshophq@gmail.com>
 */

    $url = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'detailedreview/';
    if (!($activeImage = Mage::getStoreConfig('detailedreview/rating_image/active'))) {
        $activeImage = 'default/active-star.png';
    }
    if (!($unActiveImage = Mage::getStoreConfig('detailedreview/rating_image/unactive'))) {
        $unActiveImage = 'default/unactive-star.png';
    }
    $activeImage = $url . $activeImage;
    $unActiveImage = $url . $unActiveImage;
    $activeImage24x = Mage::helper('detailedreview')->getResizedImage($activeImage,24,'');
    $unActiveImage24x = Mage::helper('detailedreview')->getResizedImage($unActiveImage,24,'');
    $activeImage17x = Mage::helper('detailedreview')->getResizedImage($activeImage,17,'');
    $unActiveImage17x = Mage::helper('detailedreview')->getResizedImage($unActiveImage,17,'');
?>
<style type="text/css">
    .reviews-container .rating-box{ background-image: url(<?php echo $unActiveImage17x ?>); height: 16px; width: 85px; }
    .reviews-container .rating-box .rating { background-image: url(<?php echo $activeImage17x ?>); height: 16px; width: 85px; }
    .block-reviewed .rating-box{ background-image: url(<?php echo $unActiveImage17x ?>); height: 16px; width: 85px; }
    .block-reviewed .rating-box .rating { background-image: url(<?php echo $activeImage17x ?>); height: 16px; width: 85px; }
    .review-top .average-rating .rating-box{ background-image: url(<?php echo $unActiveImage24x ?>); height: 22px; width: 120px; }
    .review-top .average-rating .rating-box .rating { background-image: url(<?php echo $activeImage24x ?>); height: 22px; width: 120px; }
    .overall-raiting .right li .separate-rating-star { background: url(<?php echo $unActiveImage24x ?>) no-repeat; width: 24px; height: 22px; }
    .overall-raiting .right li.active .separate-rating-star { background: url(<?php echo $activeImage24x ?>) no-repeat; }
    .category-products .ratings .amount { float:left; }
</style>