<?php
/**
 * MageWorkshop
 * Copyright (C) 2012  MageWorkshop <mageworkshophq@gmail.com>
 *
 * NOTICE OF LICENSE
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see http://opensource.org/licenses/gpl-3.0.html.
 *
 * @category   MageWorkshop
 * @package    MageWorkshop_DetailedReview
 * @copyright  Copyright (c) 2012 MageWorkshop Co. (http://mage-workshop.com)
 * @license    http://opensource.org/licenses/gpl-3.0.html GNU General Public License, version 3 (GPL-3.0)
 * @author     MageWorkshop <mageworkshophq@gmail.com>
 */


$theme = Mage::getStoreConfig('detailedreview/settings/theme');
$urlJs = Mage::helper('detailedreview')->getDetailReviewCssUrl();
$detailedreview = "<link rel='stylesheet' type='text/css' href='" . $urlJs . "/detailedreview.css'/>";
$ie7 = "<link rel='stylesheet' type='text/css' href='". $urlJs . "/detailedreview-ie7.css'/>";
if ($theme != 'standard') {
    $detailedreview .= "<link rel='stylesheet' type='text/css' href='" . $urlJs . "/" . $theme . "/detailedreview.css'/>";
    $ie7 .= "<link rel='stylesheet' type='text/css' href='" . $urlJs . "/" . $theme . "/detailedreview-ie7.css'/>";
}
?>
<script type="text/javascript">
    //<![CDATA[
    document.write("<?php echo $detailedreview; ?>");
    //]]>
</script>
<!--[if IE 7]>
<script type="text/javascript">
    document.write("<?php echo $ie7; ?>");
</script>
<![endif]-->